### ISSUE TITLE
Seems not worked after update the Google Maps API plans

### ISSUE THREAD

**Issue by vrusua** [RootStudio/Perch-Locator#14]
Hi James,

thank you for the great app! However, it seems not worked for me last time. I suppose after the updating of Google Maps API plans on June 22, 2016, see http://googlegeodevelopers.blogspot.gr/2016/06/building-for-scale-updates-to-google.html

Can you check, is the query url works well with new API keys?

Thank you.

Cheers,
Ruslan

**Comment by vrusua** [comment]
Hi again,

share the debug info to specify this:

1) once I use the API key, I got the
`{ "error_message" : "Browser API keys cannot have referer restrictions when used with this API.", "results" : [], "status" : "REQUEST_DENIED" }`

On domains created before the 22nd of June all works well without setting up the API key. But  I must apply the API key on new domains.

2) the rule which force geocode after update the store entry record `$force_geocoding = isset($data['force_geocoding']);` (at modes/locations.edit.pre.php) seems always false. If I mandatory set one to true all works as expected.

3) it seems the `PerchScheduledTasks::register_task` (at scheduled_tasks.php) don't work on Perch (2.8.30).

Thank you.

Cheers,
Ruslan

**Comment by Jamesyps** [comment]
Hi,

Thanks for the information, that's awesomely helpful. I'll try to get these issues resolved within the week and let you know when an update is ready.

Apologies if this causes you any problems in the mean time.

Kind Regards

**Comment by vrusua** [comment]
Thank you, James,

actually, no problems at all, just shared my experience to improve you addon.

Cheers
Ruslan

**Comment by vrusua** [comment]
Hi James,

update:
1) I've created the server type Google Maps API key instead the browser one, and all works well now;
2) please nevermind, "force_geocoding" works well;
3) still not worked but I need to make more testing to specify this.

my apologies for false issues, perhaps a hot weather boiled my brain.
The issue can be closed. Thank you.

Cheers
Ruslan
